[package]
name = "client"
description = "Exemplary real world client app built with Rust + Yew + WebAssembly."
categories = ["wasm", "javascript"]
version = "0.1.0"
authors = ["Jarek <jareks@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4.10", features = ["serde"] }
dotenv_codegen = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.8"
parking_lot = "0.10.0"
percent-encoding = "2.1.0"
pulldown-cmark = "0.6.1"
serde = "1.0.104"
serde_json = "1.0.44"
thiserror = "1"
yew = "0.18.0"
yew-router = { version="0.15.0", features = ["web_sys"] }
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"
wee_alloc = "0.4.5"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "Node",
  "Window",
  "HtmlCollection",
]

[dev-dependencies]
js-sys = "0.3.37"
wasm-bindgen-futures = "0.4.10"
wasm-bindgen-test = "0.3.10"
